language: node_js
node_js:
  - '10'
  - '12'
  - 'lts/*'

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: initialise
      name: 'install submodules'
      script: ./ci/init-docs
    - stage: test
      name: 'integration tests'
      script: ./ci/test
    - stage: publish
      name: 'documentation'
      script: ./ci/deploy-docs
    - script: ./ci/deploy-package
      name: 'package'

stages:
  - initialise
  - test
  - name: publish
    if: branch = master
