os: osx
language: node_js
node_js:
  - '10'
  - '12'
  - 'lts/*'

script:
  - echo "Running tests against $(node -v) ..."
  - yarn test

jobs:
  include:
    - stage: publish
      node_js: '12'
      name: 'documentation'
      script:
        - echo "Deploying documentation..."
        - cd docs
        - git pull origin HEAD:master
        - yarn install
        - cd website
        - yarn install
        - yarn build
        - cd ../..
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs/website && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
        - echo "Documentation deployed."
