language: node_js
node_js:
  - '10'
  - '12'
  - 'lts/*'

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: install
      name: 'submodules'
      script: ./ci/init-docs.sh
    - stage: test
    - stage: publish
      name: 'documentation'
      script: ./ci/deploy-docs.sh
    - script: ./ci/deploy-package.sh
      name: 'npm'

stages:
  - install
  - test
  - name: publish
    if: branch = master
